Community package manager support (and a few other new features)
rfns/forgery pull request #1
Opened 2020-03-03 22:15 UTC by timleavitt

I've forked this for my own use in some unit tests and would like to propose a few changes for the "official" version. Happy to discuss, of course! (Or to re-submit as individual smaller PRs if you would prefer that.)

Changes include:
- Support for the community package manager (zpm)
- Allowing a base URL and default set of headers to be specified when an Agent is created
- Allowing retrieval of the last %response object (for verification of %response.Status or of headers in unit tests, for example)
- Reporting/handling errors by the same means as %CSP.REST (as JSON / HTTP 500 via Http500 method of dispatch class; also still reported as a %Status for backward-compatibility)
- Fixing ClearCookies to be an instance method so it compiles

2020-03-03 23:19 UTC, rfns commented
Hello @timleavitt surely your PR would be welcomed!

But before accepting it I'll be running your branch against my test suite from here: https://github.com/rfns/frontier/blob/master/cls/UnitTest/Frontier/Router.cls and see if something breaks.

Just in case, because I might have to release a major if it does. Either way I'll be accepting your PR as soon as I can.

Keep in touch!

2020-03-09 16:40 UTC, rfns approved these changes

2020-03-09 16:51 UTC, rfns requested changes
@timleavitt Since you're including the ZPM support, take the XMLs out and you're free to go.

2020-03-09 17:00 UTC, timleavitt commented
@rfns can you clarify? The only XML is module.xml, which is as it should be (see for example: https://community.intersystems.com/post/anatomy-zpm-module-packaging-your-intersystems-solution)

2020-03-09 19:48 UTC, rfns commented
> @rfns can you clarify? The only XML is module.xml, which is as it should be (see for example: https://community.intersystems.com/post/anatomy-zpm-module-packaging-your-intersystems-solution)
> 
> Is your intent to not add ZPM support yet?

No, it's the opposite actually. Because I meant to remove the old XML files that came along with your fork.

![image](https://user-images.githubusercontent.com/3527583/76249502-37a21280-6222-11ea-9630-3562f05bee19.png)

These files are old and are not in sync with your changes now (last changes have been made 5 months ago after all).

Unless you think it's worth updating them as well instead. I'm open for discussion just like you do.

2020-03-09 20:03 UTC, timleavitt commented
@rfns ahh, that makes sense. Thank you. I was confused because I didn't change those at all.

I think it makes sense to update them (to support installation on clients not using the community package manager, e.g., because they're on older platform versions); however, I'm not clear on how you have produced them. I think it would be reasonable to commit this and then produce new artifact versions, or (alternatively) to not commit artifacts but instead treat them as "releases" on GitHub.

2020-03-09 20:24 UTC, rfns commented
@timleavitt Yes, I agree with you. I think I'll need to set up a GitHub action to build that release artifact soon.

While I'm doing that you can export create the forgery project using the Studio and export it from there. If you don't have it you can create one and add the 4 classes manually (not the package).

I'll be removing that XML along with a new version that adds a pipeline to build the release artifact accordingly. This shouldn't take too long because I'm already working on something close to this.

It should generate a XML that's similar to what we have today. You can ignore that `forgery-prod.xml` it makes no sense to have it for now as there's no UnitTests. 

Just so you know, The `forgery.-prod.xml` is a variant that has no project or test cases classes.

2020-03-09 20:30 UTC, timleavitt commented
FYI, there may be support in the community package manager for packaging as a studio project. (Need to check if that made it in there...)

2020-03-09 20:55 UTC, rfns commented
@timleavitt If you have difficulties find it on ZPM, it's also possible to export the project like this:

```objectscript
  set project = ##class(%Studio.Project).%OpenId("forgery")
  do project.Export("/location/of/the/artifact.xml")
```

But using the ZPM CLI should be easier in the pipeline than having to actually create a routine just to run the the two lines above.

2020-03-12 14:19 UTC, timleavitt commented
@rfns I'm a bit behind on this given current events. Still aiming to add the project exports today/tomorrow.

2020-03-13 14:56 UTC, rfns commented
@timleavitt No problem, I think I might be able to generate that XML.

I'm making some changes on my [iris-ci](https://github.com/rfns/iris-ci) project so that I can use it for purposes other than UnitTesting, including the XML generation.

2020-03-18 18:46 UTC, rfns commented
@timleavitt good news! I got the XML generation working so I'll be setting up an action script tonight and merge your PR as well.

2020-03-18 18:49 UTC, timleavitt commented
@rfns outstanding, thank you!

2020-03-18 19:55 UTC, merged